\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename org-node.info
@settitle org-node
@documentencoding UTF-8
@documentlanguage en
@c %**end of header

@dircategory Emacs
@direntry
* Org-node: (org-node). Link org-id entries into a network.
@end direntry

@finalout
@titlepage
@title org-node
@author Martin Edström
@end titlepage

@ifnottex
@node Top
@top org-node
@end ifnottex

@menu
* News for v3::
@end menu

@node News for v3
@chapter News for v3 :export:

A lot of code has been spun into a new library @uref{https://github.com/meedstrom/indexed}@comma{} now a dependency.  Reduces codebase by 25%.  This may allow other projects to create interesting stuff without org-node.

Update initfiles when you can.  Direct renames:

@multitable {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaa}
@headitem Old user option
@tab New user option
@item org-node-extra-id-dirs
@tab indexed-org-dirs
@item org-node-extra-id-dirs-exclude
@tab indexed-org-dirs-exclude
@item org-node-link-types
@tab indexed-seek-link-types
@end multitable

Also you'll get messages about it@comma{} but enable two modes before @samp{org-node-cache-mode}:

@lisp
(indexed-roam-mode)
(indexed-updater-mode)
(org-node-cache-mode)
@end lisp

Node seqs@comma{} if you use them@comma{} now require turning on explicitly.

@lisp
(org-node-seq-mode)
@end lisp

For reference@comma{} check out the full list of obsoletions near the bottom of file @samp{org-node-changes.el}.

@bye
