* Before 1.0

- [ ] Fix =org-node-tag-add=

- [ ] Refile

* Other
- [ ] Spin out a library for async processing (=org-node--scan= and friends)

- [ ] org-node-series-dispatch: Free up keys "j" "n" "p", "c"

- [ ] A workflow to allow pseudo-untitled (numeric-titled) nodes

  Already =org-node-grep= can be considered an equivalent to =org-node-find=, so we "just" need an equivalent to =org-node-insert-link=.  Basically, capture, refile, and insert-link would probably all use the same mechanism for *identifying a node by a grep result.*

- [ ] Accept more ref variants as the same ref

  If a roam-ref exists like =//www.website.com=, allow counting a link =//www.website.com?key=val&key2=val2#hash= as a reflink to the same, unless the latter has a roam-ref of its own.

  Would prolly be a fairly expensive operation.  After building ref<>id and dest<>links, run thru every dest and check if an existing ref is a prefix of it, then simply nconc the value with the value for the corresponding dest.  But having to check for other dests that may also be a prefix is where it would get expensive... O(n^2) I guess.

  Hm... Sort all dests alphabetically.  All near-matches will be very close to each other, and indeed an alphabetic sort even results in a sort-by-length within each possible "group". So just run down progressively shorter prefixes until the length goes up again, then we know we're in another group.  Rough idea, but O(n^2) looks beatable.

- [ ] In 2025: drop Emacs 28

  Seems that Debian stable will be stuck on Emacs 28 until mid-2025,
  then likely leap to Emacs 30.

  List of 28-isms and 29-isms to drop in future

  - =(cadar (org-collect-keywords "TITLE"))= -> =(org-get-title)=
  - simplify =(org-node--strip-diacritics)=
  - =;;;###autoload (autoload 'org-node-series-dispatch "org-node" nil t)=
    - In Emacs 30, replace with just =;;;###autoload=
  - any usages of =compat-call=
  - =;; Package-Requires: ((transient) (seq))=
  - what the compiler tells you is obsolete
